// amoeba_bot_1_train: self-play, training, and the gate that decides which
// model amoeba_bot_1 gets to play with. It never talks to Game Arena - it does
// not even link the SDK - and the player never trains. They share a checkpoint
// directory and nothing else, so running both at once is just running two
// programs, and killing either one leaves the other working.
//
// One generation is three steps:
//
//   1. play `AMOEBA_SELFPLAY_GAMES` games against itself with the champion, and
//      push every position into the replay buffer
//   2. take `AMOEBA_TRAIN_STEPS` gradient steps on batches drawn from the buffer
//   3. play the result against the champion; promote it only if it wins
//
// Step 3 is the point of the whole file. Training does not improve
// monotonically, so "the newest model" and "the strongest model" are different
// things, and an AlphaZero bug reliably produces a healthy-looking loss curve
// while the bot gets worse. A generation beating the one before it over a real
// match is the only honest signal here.
//
// Self-play is one game at a time. That is the obvious thing to fix first once
// the network exists: the evaluator interface already takes a span of boards, so
// the shape to move to is many concurrent games collecting leaves into one
// batched forward pass, rather than one position per pass.

#include "checkpoints.hpp"
#include "mcts.hpp"
#include "network.hpp"

#include <amoeba/amoeba.hpp>

#include <algorithm>
#include <array>
#include <charconv>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <memory>
#include <numeric>
#include <print>
#include <random>
#include <span>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace bot
{

namespace
{

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

template <typename T>
T fromEnvironment(const char* name, T fallback)
{
    const char* text = std::getenv(name);
    if (text == nullptr)
        return fallback;

    T parsed{};
    if constexpr (std::is_floating_point_v<T>)
    {
        char* end = nullptr;
        parsed    = static_cast<T>(std::strtod(text, &end));
        if (end == text || *end != '\0')
        {
            std::println(stderr, "[train] {} is not a number, using {}", name, fallback);
            return fallback;
        }
    }
    else
    {
        const std::string_view value{text};
        if (std::from_chars(value.data(), value.data() + value.size(), parsed).ec != std::errc{})
        {
            std::println(stderr, "[train] {} is not a number, using {}", name, fallback);
            return fallback;
        }
    }
    return parsed;
}

struct Settings
{
    int selfPlayGames       = fromEnvironment("AMOEBA_SELFPLAY_GAMES", 200);
    int selfPlaySimulations = fromEnvironment("AMOEBA_SELFPLAY_SIMULATIONS", 400);
    int trainSteps          = fromEnvironment("AMOEBA_TRAIN_STEPS", 1000);
    int batchSize           = fromEnvironment("AMOEBA_BATCH", 512);
    int gateGames           = fromEnvironment("AMOEBA_GATE_GAMES", 100);
    int gateSimulations     = fromEnvironment("AMOEBA_GATE_SIMULATIONS", 400);

    // 55% is the usual bar: enough that a run of luck over 100 games does not
    // promote a model that is actually the same strength.
    float gateThreshold = fromEnvironment("AMOEBA_GATE_THRESHOLD", 0.55f);

    // How long a game samples its move from the visit counts instead of taking
    // the best one. Sampling is what makes two games differ; past the opening
    // it is just playing worse moves for no reason.
    int openingPlies = fromEnvironment("AMOEBA_OPENING_PLIES", 15);

    // Positions kept. A generation of 200 games contributes roughly 20k of them,
    // so this holds about the last 25 generations.
    int bufferCapacity = fromEnvironment("AMOEBA_BUFFER", 500000);

    uint64_t seed = fromEnvironment<uint64_t>("AMOEBA_SEED", 20260819);
};

// Self-play is bounded by its simulation count, not by the clock; this exists
// only so that an evaluator that wedges cannot hang the trainer forever.
constexpr std::chrono::minutes kSanityDeadline{5};

// ---------------------------------------------------------------------------
// Replay buffer
//
// A ring over the last N positions. Old positions are dropped rather than kept
// because they were generated by networks several generations weaker, and
// training on them holds the current one back.
// ---------------------------------------------------------------------------

class ReplayBuffer
{
public:
    explicit ReplayBuffer(size_t capacity) : m_capacity(capacity) {}

    size_t size() const { return m_samples.size(); }

    void push(const Sample& sample)
    {
        if (m_samples.size() < m_capacity)
            m_samples.push_back(sample);
        else
            m_samples[m_next] = sample;
        m_next = (m_next + 1) % m_capacity;
    }

    // With replacement: a batch of 512 out of 500k duplicates about nothing, and
    // sampling without replacement would need a shuffle of the whole buffer.
    void drawBatch(std::span<Sample> out, std::mt19937_64& rng) const
    {
        std::uniform_int_distribution<size_t> pick(0, m_samples.size() - 1);
        for (Sample& sample : out)
            sample = m_samples[pick(rng)];
    }

    // Written beside the file and renamed over it, so a crash halfway through
    // leaves the previous buffer intact rather than a truncated one.
    void save(const std::filesystem::path& file) const
    {
        std::filesystem::path staging = file;
        staging += ".staging";

        std::ofstream out(staging, std::ios::binary);
        out.write(reinterpret_cast<const char*>(m_samples.data()),
                  static_cast<std::streamsize>(m_samples.size() * sizeof(Sample)));
        out.close();

        std::filesystem::rename(staging, file);
    }

    void load(const std::filesystem::path& file)
    {
        const size_t available = std::filesystem::file_size(file) / sizeof(Sample);
        const size_t keep      = std::min(available, m_capacity);

        m_samples.resize(keep);
        std::ifstream in(file, std::ios::binary);
        in.seekg(static_cast<std::streamoff>((available - keep) * sizeof(Sample)));
        in.read(reinterpret_cast<char*>(m_samples.data()),
                static_cast<std::streamsize>(keep * sizeof(Sample)));

        m_next = keep % m_capacity;
    }

private:
    std::vector<Sample> m_samples;
    size_t              m_capacity;
    size_t              m_next = 0;
};

// ---------------------------------------------------------------------------
// Playing a game
// ---------------------------------------------------------------------------

struct GameRecord
{
    std::vector<std::pair<amoeba::Board, VisitCounts>> plies;
    amoeba::State                                      outcome;
};

// One game between two searches. Self-play passes the same evaluator twice and
// keeps the plies; the gate passes two different ones and reads only the
// outcome.
GameRecord playGame(Search& white, Search& black, int openingPlies, std::mt19937_64& rng)
{
    GameRecord            record;
    amoeba::Board         board = amoeba::openingBoard();
    std::vector<uint64_t> history{board.hash};

    while (board.state == amoeba::State::Ongoing)
    {
        Search&           search = board.whiteToMove ? white : black;
        const VisitCounts counts = search.run(board, history);
        record.plies.emplace_back(board, counts);

        const uint16_t move =
            board.ply < openingPlies ? sampleMove(counts, 1.0f, rng) : bestMove(counts);

        board = amoeba::apply(board, amoeba::Move::fromId(move), history);
        history.push_back(board.hash);
    }

    record.outcome = board.state;
    return record;
}

std::array<float, amoeba::kNumMoveIds> policyTarget(const VisitCounts& counts)
{
    const float total = static_cast<float>(std::accumulate(counts.begin(), counts.end(), uint64_t{0}));

    std::array<float, amoeba::kNumMoveIds> policy{};
    for (size_t id = 0; id < counts.size(); ++id)
        policy[id] = static_cast<float>(counts[id]) / total;
    return policy;
}

// Both sides are the same network. They still need two searches, because a
// Search owns its tree, and two different seeds, because sharing one would give
// White and Black the same stream of root noise.
void selfPlay(Evaluator& champion, const Settings& settings, uint64_t seed, ReplayBuffer& buffer)
{
    const auto config = [&](uint64_t searchSeed) {
        return Config{.simulations     = settings.selfPlaySimulations,
                      .deadline        = kSanityDeadline,
                      .rootNoiseWeight = 0.25f,
                      .seed            = searchSeed};
    };

    Search          white(champion, config(seed));
    Search          black(champion, config(seed ^ 0x9e3779b97f4a7c15ULL));
    std::mt19937_64 rng(seed);

    const GameRecord record = playGame(white, black, settings.openingPlies, rng);

    // The value target is the game's result seen by whoever was to move in that
    // position, which is what the search's own values mean. Signing it as "good
    // for White" instead would train a bot that plays badly on purpose for one
    // colour, and the loss curve would look fine throughout.
    for (const auto& [board, counts] : record.plies)
        buffer.push(Sample{board, policyTarget(counts), outcomeFor(record.outcome, board.whiteToMove)});
}

// ---------------------------------------------------------------------------
// The gate
// ---------------------------------------------------------------------------

struct MatchScore
{
    int wins   = 0;
    int draws  = 0;
    int losses = 0;

    float points() const
    {
        return (static_cast<float>(wins) + 0.5f * static_cast<float>(draws))
             / static_cast<float>(wins + draws + losses);
    }
};

// Colours alternate, because White moves first and that is worth something.
//
// Both sides play their best move, so the sampled opening is the only thing
// making one game differ from the next - without it the whole match would be a
// single game replayed `gateGames` times and the score would be 100% or 0%.
MatchScore playMatch(Evaluator& challenger, Evaluator& champion, const Settings& settings, uint64_t seed)
{
    MatchScore score;

    for (int game = 0; game < settings.gateGames; ++game)
    {
        const uint64_t gameSeed = seed + static_cast<uint64_t>(game);
        const Config   config{.simulations = settings.gateSimulations,
                              .deadline    = kSanityDeadline,
                              .seed        = gameSeed};

        Search challengerSearch(challenger, config);
        Search championSearch(champion, config);

        const bool challengerIsWhite = (game % 2) == 0;
        Search&    white             = challengerIsWhite ? challengerSearch : championSearch;
        Search&    black             = challengerIsWhite ? championSearch : challengerSearch;

        std::mt19937_64  rng(gameSeed);
        const GameRecord record = playGame(white, black, settings.openingPlies, rng);

        if (record.outcome == amoeba::State::Draw)
            ++score.draws;
        else if ((record.outcome == amoeba::State::WhiteWins) == challengerIsWhite)
            ++score.wins;
        else
            ++score.losses;
    }

    return score;
}

// ---------------------------------------------------------------------------

std::filesystem::path bufferFile(const Checkpoints& checkpoints)
{
    return checkpoints.directory() / "replay.bin";
}

} // namespace

} // namespace bot

int main()
{
    const bot::Settings    settings;
    const bot::Checkpoints checkpoints = bot::Checkpoints::fromEnvironment();
    std::mt19937_64        rng(settings.seed);

    // Generation 0 is untrained, and is promoted without a match because there
    // is nothing yet for it to beat. It plays terribly; that is the baseline.
    if (checkpoints.latestGeneration() < 0)
    {
        bot::newNetwork(settings.seed)->save(checkpoints.forGeneration(0));
        checkpoints.promote(0);
        std::println("[train] wrote and promoted generation 0");
    }

    bot::ReplayBuffer buffer(static_cast<size_t>(settings.bufferCapacity));
    if (std::filesystem::exists(bot::bufferFile(checkpoints)))
    {
        buffer.load(bot::bufferFile(checkpoints));
        std::println("[train] recovered {} positions", buffer.size());
    }

    // One network trained continuously across generations. Resetting it to the
    // champion after a failed gate would throw that generation's training away,
    // and a plateau that takes two generations to cross would never be crossed.
    const std::unique_ptr<bot::Network> learner =
        bot::loadNetwork(checkpoints.forGeneration(checkpoints.latestGeneration()));
    bot::Trainer trainer(*learner);

    std::vector<bot::Sample> batch(static_cast<size_t>(settings.batchSize));

    for (;;)
    {
        // Read from disk rather than counting, so that a generation which was
        // skipped for want of data does not leave a hole in the numbering.
        const int generation = checkpoints.latestGeneration() + 1;

        const std::unique_ptr<bot::Network> champion = bot::loadNetwork(*checkpoints.best());

        for (int game = 0; game < settings.selfPlayGames; ++game)
            bot::selfPlay(*champion, settings, rng(), buffer);
        buffer.save(bot::bufferFile(checkpoints));
        std::println("[train] generation {}: {} games played, {} positions held",
                     generation, settings.selfPlayGames, buffer.size());

        if (buffer.size() < batch.size())
        {
            std::println("[train] not enough positions for a batch yet, playing more");
            continue;
        }

        float loss = 0.0f;
        for (int step = 0; step < settings.trainSteps; ++step)
        {
            buffer.drawBatch(batch, rng);
            loss = trainer.step(batch);
        }
        learner->save(checkpoints.forGeneration(generation));
        std::println("[train] generation {}: {} steps, loss {:.4f}", generation, settings.trainSteps, loss);

        const bot::MatchScore score = bot::playMatch(*learner, *champion, settings, rng());
        const bool            promoted = score.points() >= settings.gateThreshold;
        if (promoted)
            checkpoints.promote(generation);

        std::println("[train] generation {}: {}-{}-{} vs champion ({:.1f}%) - {}",
                     generation, score.wins, score.draws, score.losses, 100.0f * score.points(),
                     promoted ? "promoted" : "kept the champion");
    }
}
