#ifndef TRAINING_HPP
#define TRAINING_HPP

#include "amoeba_network.hpp"

#include <cstddef>
#include <cstdint>
#include <vector>

namespace amoeba
{

// Settings are read from the existing environment variables by the constructor.
// Keeping the values together lets main.cpp own the generation loop without
// knowing how each individual setting is loaded.
struct TrainingSettings
{
    TrainingSettings();

    // Reproducible randomness shared by self-play, batches, and gate games.
    uint64_t seed;

    // Self-play spends enough simulations to produce useful visit targets. Root
    // noise and early sampling keep independent games from repeating one line.
    MCTSConfig searchConfig;
    int selfPlayGameCount;
    int samplingPlyCount;
    float rootNoise;
    int concurrentSelfPlayGames;

    // Minibatch optimization stops early when held-out loss stops improving.
    int maximumTrainingSteps;
    int trainingBatchSize;
    float learningRate;
    float weightDecay;

    // Recent positions survive across generations until this FIFO limit.
    size_t replayBufferCapacity;

    // The gate compares candidate and champion in games; only a candidate that
    // reaches promotionThreshold replaces the live checkpoint.
    int gateGameCount;
    float promotionThreshold;
    int concurrentGateGames;
    int gateSimulationCount;
};

// One position generated by self-play. main.cpp owns the replay buffer, so this
// type is part of the helper API rather than hidden inside training.cpp.
struct TrainingSample
{
    Board board;
    VisitCounts visits;
    float outcome = 0.0f;
    int gameId = 0; // Unique across generations for whole-game validation splits.
};

std::vector<TrainingSample> generateSelfPlaySamples(
    const AmoebaNetwork& champion, const TrainingSettings& settings, uint64_t seed);

// Updates candidate in place, leaving it with the parameter values from the
// training step that achieved the best held-out loss.
void trainCandidate(AmoebaNetwork& candidate,
                    const std::vector<TrainingSample>& samples,
                    const TrainingSettings& settings, uint64_t seed);

// Returns the candidate's score against the champion, with draws worth one half.
double evaluateCandidate(const AmoebaNetwork& candidate,
                         const AmoebaNetwork& champion,
                         const TrainingSettings& settings, uint64_t seed);

void reportMemory(const char* phase);

} // namespace amoeba

#endif // TRAINING_HPP
